/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as OffreSiteInternetRouteImport } from './routes/offre-site-internet'
import { Route as OffreLogoRouteImport } from './routes/offre-logo'
import { Route as NousContacterRouteImport } from './routes/nous-contacter'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InscriptionPartenaireRouteImport } from './routes/inscription-partenaire'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DomiciliationEntrepriseAbidjanRouteImport } from './routes/domiciliation-entreprise-abidjan'
import { Route as DemandeSoumissionsRouteImport } from './routes/demande-soumissions'
import { Route as DeclarationFiscaleCoteDivoireRouteImport } from './routes/declaration-fiscale-cote-divoire'
import { Route as CreerSonEntrepriseCoteDivoireRouteImport } from './routes/creer-son-entreprise-cote-divoire'
import { Route as CreationEntrepriseDiasporaIvoirienneRouteImport } from './routes/creation-entreprise-diaspora-ivoirienne'
import { Route as CreationEntrepriseCoteDivoireRouteImport } from './routes/creation-entreprise-cote-divoire'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ComptabiliteEntrepriseAbidjanRouteImport } from './routes/comptabilite-entreprise-abidjan'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as ChangerMotDePasseRouteImport } from './routes/changer-mot-de-passe'
import { Route as CabinetsComptablesPartenairesRouteImport } from './routes/cabinets-comptables-partenaires'
import { Route as CabinetComptableAbidjanRouteImport } from './routes/cabinet-comptable-abidjan'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as EnWebsiteOfferRouteImport } from './routes/en/website-offer'
import { Route as EnThankYouRouteImport } from './routes/en/thank-you'
import { Route as EnStartABusinessIvoryCoastRouteImport } from './routes/en/start-a-business-ivory-coast'
import { Route as EnLogoOfferRouteImport } from './routes/en/logo-offer'
import { Route as EnGetQuotesRouteImport } from './routes/en/get-quotes'
import { Route as EnContactUsRouteImport } from './routes/en/contact-us'
import { Route as EnCompanyRegistrationIvoryCoastRouteImport } from './routes/en/company-registration-ivory-coast'
import { Route as EnAccountingFirmAbidjanRouteImport } from './routes/en/accounting-firm-abidjan'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as AuthenticatedTutorielPartenaireRouteImport } from './routes/_authenticated.tutoriel-partenaire'
import { Route as AuthenticatedRechargerRouteImport } from './routes/_authenticated.recharger'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated.marketplace'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated.historique'
import { Route as AuthenticatedEspacePartenaireRouteImport } from './routes/_authenticated.espace-partenaire'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicTestPartnerWebhookRouteImport } from './routes/api/public/test-partner-webhook'
import { Route as ApiPublicMetaCapiRouteImport } from './routes/api/public/meta-capi'
import { Route as ApiPublicLeadUpsellRouteImport } from './routes/api/public/lead-upsell'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicChariowWebhookRouteImport } from './routes/api/public/chariow-webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const OffreSiteInternetRoute = OffreSiteInternetRouteImport.update({
  id: '/offre-site-internet',
  path: '/offre-site-internet',
  getParentRoute: () => rootRouteImport,
} as any)
const OffreLogoRoute = OffreLogoRouteImport.update({
  id: '/offre-logo',
  path: '/offre-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const NousContacterRoute = NousContacterRouteImport.update({
  id: '/nous-contacter',
  path: '/nous-contacter',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionPartenaireRoute = InscriptionPartenaireRouteImport.update({
  id: '/inscription-partenaire',
  path: '/inscription-partenaire',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DomiciliationEntrepriseAbidjanRoute =
  DomiciliationEntrepriseAbidjanRouteImport.update({
    id: '/domiciliation-entreprise-abidjan',
    path: '/domiciliation-entreprise-abidjan',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemandeSoumissionsRoute = DemandeSoumissionsRouteImport.update({
  id: '/demande-soumissions',
  path: '/demande-soumissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclarationFiscaleCoteDivoireRoute =
  DeclarationFiscaleCoteDivoireRouteImport.update({
    id: '/declaration-fiscale-cote-divoire',
    path: '/declaration-fiscale-cote-divoire',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreerSonEntrepriseCoteDivoireRoute =
  CreerSonEntrepriseCoteDivoireRouteImport.update({
    id: '/creer-son-entreprise-cote-divoire',
    path: '/creer-son-entreprise-cote-divoire',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreationEntrepriseDiasporaIvoirienneRoute =
  CreationEntrepriseDiasporaIvoirienneRouteImport.update({
    id: '/creation-entreprise-diaspora-ivoirienne',
    path: '/creation-entreprise-diaspora-ivoirienne',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreationEntrepriseCoteDivoireRoute =
  CreationEntrepriseCoteDivoireRouteImport.update({
    id: '/creation-entreprise-cote-divoire',
    path: '/creation-entreprise-cote-divoire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptabiliteEntrepriseAbidjanRoute =
  ComptabiliteEntrepriseAbidjanRouteImport.update({
    id: '/comptabilite-entreprise-abidjan',
    path: '/comptabilite-entreprise-abidjan',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangerMotDePasseRoute = ChangerMotDePasseRouteImport.update({
  id: '/changer-mot-de-passe',
  path: '/changer-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetsComptablesPartenairesRoute =
  CabinetsComptablesPartenairesRouteImport.update({
    id: '/cabinets-comptables-partenaires',
    path: '/cabinets-comptables-partenaires',
    getParentRoute: () => rootRouteImport,
  } as any)
const CabinetComptableAbidjanRoute = CabinetComptableAbidjanRouteImport.update({
  id: '/cabinet-comptable-abidjan',
  path: '/cabinet-comptable-abidjan',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const EnWebsiteOfferRoute = EnWebsiteOfferRouteImport.update({
  id: '/en/website-offer',
  path: '/en/website-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnThankYouRoute = EnThankYouRouteImport.update({
  id: '/en/thank-you',
  path: '/en/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStartABusinessIvoryCoastRoute =
  EnStartABusinessIvoryCoastRouteImport.update({
    id: '/en/start-a-business-ivory-coast',
    path: '/en/start-a-business-ivory-coast',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnLogoOfferRoute = EnLogoOfferRouteImport.update({
  id: '/en/logo-offer',
  path: '/en/logo-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGetQuotesRoute = EnGetQuotesRouteImport.update({
  id: '/en/get-quotes',
  path: '/en/get-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactUsRoute = EnContactUsRouteImport.update({
  id: '/en/contact-us',
  path: '/en/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCompanyRegistrationIvoryCoastRoute =
  EnCompanyRegistrationIvoryCoastRouteImport.update({
    id: '/en/company-registration-ivory-coast',
    path: '/en/company-registration-ivory-coast',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnAccountingFirmAbidjanRoute = EnAccountingFirmAbidjanRouteImport.update({
  id: '/en/accounting-firm-abidjan',
  path: '/en/accounting-firm-abidjan',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorielPartenaireRoute =
  AuthenticatedTutorielPartenaireRouteImport.update({
    id: '/tutoriel-partenaire',
    path: '/tutoriel-partenaire',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRechargerRoute = AuthenticatedRechargerRouteImport.update({
  id: '/recharger',
  path: '/recharger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEspacePartenaireRoute =
  AuthenticatedEspacePartenaireRouteImport.update({
    id: '/espace-partenaire',
    path: '/espace-partenaire',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTestPartnerWebhookRoute =
  ApiPublicTestPartnerWebhookRouteImport.update({
    id: '/api/public/test-partner-webhook',
    path: '/api/public/test-partner-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaCapiRoute = ApiPublicMetaCapiRouteImport.update({
  id: '/api/public/meta-capi',
  path: '/api/public/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadUpsellRoute = ApiPublicLeadUpsellRouteImport.update({
  id: '/api/public/lead-upsell',
  path: '/api/public/lead-upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChariowWebhookRoute = ApiPublicChariowWebhookRouteImport.update({
  id: '/api/public/chariow-webhook',
  path: '/api/public/chariow-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/cabinet-comptable-abidjan': typeof CabinetComptableAbidjanRoute
  '/cabinets-comptables-partenaires': typeof CabinetsComptablesPartenairesRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comptabilite-entreprise-abidjan': typeof ComptabiliteEntrepriseAbidjanRoute
  '/connexion': typeof ConnexionRoute
  '/creation-entreprise-cote-divoire': typeof CreationEntrepriseCoteDivoireRoute
  '/creation-entreprise-diaspora-ivoirienne': typeof CreationEntrepriseDiasporaIvoirienneRoute
  '/creer-son-entreprise-cote-divoire': typeof CreerSonEntrepriseCoteDivoireRoute
  '/declaration-fiscale-cote-divoire': typeof DeclarationFiscaleCoteDivoireRoute
  '/demande-soumissions': typeof DemandeSoumissionsRoute
  '/domiciliation-entreprise-abidjan': typeof DomiciliationEntrepriseAbidjanRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-partenaire': typeof InscriptionPartenaireRoute
  '/mcp': typeof McpRoute
  '/merci': typeof MerciRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nous-contacter': typeof NousContacterRoute
  '/offre-logo': typeof OffreLogoRoute
  '/offre-site-internet': typeof OffreSiteInternetRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace-partenaire': typeof AuthenticatedEspacePartenaireRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/recharger': typeof AuthenticatedRechargerRoute
  '/tutoriel-partenaire': typeof AuthenticatedTutorielPartenaireRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-abidjan': typeof EnAccountingFirmAbidjanRoute
  '/en/company-registration-ivory-coast': typeof EnCompanyRegistrationIvoryCoastRoute
  '/en/contact-us': typeof EnContactUsRoute
  '/en/get-quotes': typeof EnGetQuotesRoute
  '/en/logo-offer': typeof EnLogoOfferRoute
  '/en/start-a-business-ivory-coast': typeof EnStartABusinessIvoryCoastRoute
  '/en/thank-you': typeof EnThankYouRoute
  '/en/website-offer': typeof EnWebsiteOfferRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en/': typeof EnIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/chariow-webhook': typeof ApiPublicChariowWebhookRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/lead-upsell': typeof ApiPublicLeadUpsellRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/test-partner-webhook': typeof ApiPublicTestPartnerWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/cabinet-comptable-abidjan': typeof CabinetComptableAbidjanRoute
  '/cabinets-comptables-partenaires': typeof CabinetsComptablesPartenairesRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comptabilite-entreprise-abidjan': typeof ComptabiliteEntrepriseAbidjanRoute
  '/connexion': typeof ConnexionRoute
  '/creation-entreprise-cote-divoire': typeof CreationEntrepriseCoteDivoireRoute
  '/creation-entreprise-diaspora-ivoirienne': typeof CreationEntrepriseDiasporaIvoirienneRoute
  '/creer-son-entreprise-cote-divoire': typeof CreerSonEntrepriseCoteDivoireRoute
  '/declaration-fiscale-cote-divoire': typeof DeclarationFiscaleCoteDivoireRoute
  '/demande-soumissions': typeof DemandeSoumissionsRoute
  '/domiciliation-entreprise-abidjan': typeof DomiciliationEntrepriseAbidjanRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-partenaire': typeof InscriptionPartenaireRoute
  '/mcp': typeof McpRoute
  '/merci': typeof MerciRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nous-contacter': typeof NousContacterRoute
  '/offre-logo': typeof OffreLogoRoute
  '/offre-site-internet': typeof OffreSiteInternetRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace-partenaire': typeof AuthenticatedEspacePartenaireRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/recharger': typeof AuthenticatedRechargerRoute
  '/tutoriel-partenaire': typeof AuthenticatedTutorielPartenaireRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-abidjan': typeof EnAccountingFirmAbidjanRoute
  '/en/company-registration-ivory-coast': typeof EnCompanyRegistrationIvoryCoastRoute
  '/en/contact-us': typeof EnContactUsRoute
  '/en/get-quotes': typeof EnGetQuotesRoute
  '/en/logo-offer': typeof EnLogoOfferRoute
  '/en/start-a-business-ivory-coast': typeof EnStartABusinessIvoryCoastRoute
  '/en/thank-you': typeof EnThankYouRoute
  '/en/website-offer': typeof EnWebsiteOfferRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en': typeof EnIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/chariow-webhook': typeof ApiPublicChariowWebhookRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/lead-upsell': typeof ApiPublicLeadUpsellRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/test-partner-webhook': typeof ApiPublicTestPartnerWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/cabinet-comptable-abidjan': typeof CabinetComptableAbidjanRoute
  '/cabinets-comptables-partenaires': typeof CabinetsComptablesPartenairesRoute
  '/changer-mot-de-passe': typeof ChangerMotDePasseRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comptabilite-entreprise-abidjan': typeof ComptabiliteEntrepriseAbidjanRoute
  '/connexion': typeof ConnexionRoute
  '/creation-entreprise-cote-divoire': typeof CreationEntrepriseCoteDivoireRoute
  '/creation-entreprise-diaspora-ivoirienne': typeof CreationEntrepriseDiasporaIvoirienneRoute
  '/creer-son-entreprise-cote-divoire': typeof CreerSonEntrepriseCoteDivoireRoute
  '/declaration-fiscale-cote-divoire': typeof DeclarationFiscaleCoteDivoireRoute
  '/demande-soumissions': typeof DemandeSoumissionsRoute
  '/domiciliation-entreprise-abidjan': typeof DomiciliationEntrepriseAbidjanRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/inscription-partenaire': typeof InscriptionPartenaireRoute
  '/mcp': typeof McpRoute
  '/merci': typeof MerciRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nous-contacter': typeof NousContacterRoute
  '/offre-logo': typeof OffreLogoRoute
  '/offre-site-internet': typeof OffreSiteInternetRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/espace-partenaire': typeof AuthenticatedEspacePartenaireRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/recharger': typeof AuthenticatedRechargerRoute
  '/_authenticated/tutoriel-partenaire': typeof AuthenticatedTutorielPartenaireRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-abidjan': typeof EnAccountingFirmAbidjanRoute
  '/en/company-registration-ivory-coast': typeof EnCompanyRegistrationIvoryCoastRoute
  '/en/contact-us': typeof EnContactUsRoute
  '/en/get-quotes': typeof EnGetQuotesRoute
  '/en/logo-offer': typeof EnLogoOfferRoute
  '/en/start-a-business-ivory-coast': typeof EnStartABusinessIvoryCoastRoute
  '/en/thank-you': typeof EnThankYouRoute
  '/en/website-offer': typeof EnWebsiteOfferRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en/': typeof EnIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/chariow-webhook': typeof ApiPublicChariowWebhookRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/lead-upsell': typeof ApiPublicLeadUpsellRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/test-partner-webhook': typeof ApiPublicTestPartnerWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/cabinet-comptable-abidjan'
    | '/cabinets-comptables-partenaires'
    | '/changer-mot-de-passe'
    | '/comment-ca-marche'
    | '/comptabilite-entreprise-abidjan'
    | '/connexion'
    | '/creation-entreprise-cote-divoire'
    | '/creation-entreprise-diaspora-ivoirienne'
    | '/creer-son-entreprise-cote-divoire'
    | '/declaration-fiscale-cote-divoire'
    | '/demande-soumissions'
    | '/domiciliation-entreprise-abidjan'
    | '/faq'
    | '/guides'
    | '/inscription-partenaire'
    | '/mcp'
    | '/merci'
    | '/mot-de-passe-oublie'
    | '/nous-contacter'
    | '/offre-logo'
    | '/offre-site-internet'
    | '/reinitialiser-mot-de-passe'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/espace-partenaire'
    | '/historique'
    | '/marketplace'
    | '/recharger'
    | '/tutoriel-partenaire'
    | '/en/about'
    | '/en/accounting-firm-abidjan'
    | '/en/company-registration-ivory-coast'
    | '/en/contact-us'
    | '/en/get-quotes'
    | '/en/logo-offer'
    | '/en/start-a-business-ivory-coast'
    | '/en/thank-you'
    | '/en/website-offer'
    | '/guides/$slug'
    | '/en/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/chariow-webhook'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/lead-upsell'
    | '/api/public/meta-capi'
    | '/api/public/test-partner-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/cabinet-comptable-abidjan'
    | '/cabinets-comptables-partenaires'
    | '/changer-mot-de-passe'
    | '/comment-ca-marche'
    | '/comptabilite-entreprise-abidjan'
    | '/connexion'
    | '/creation-entreprise-cote-divoire'
    | '/creation-entreprise-diaspora-ivoirienne'
    | '/creer-son-entreprise-cote-divoire'
    | '/declaration-fiscale-cote-divoire'
    | '/demande-soumissions'
    | '/domiciliation-entreprise-abidjan'
    | '/faq'
    | '/guides'
    | '/inscription-partenaire'
    | '/mcp'
    | '/merci'
    | '/mot-de-passe-oublie'
    | '/nous-contacter'
    | '/offre-logo'
    | '/offre-site-internet'
    | '/reinitialiser-mot-de-passe'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/espace-partenaire'
    | '/historique'
    | '/marketplace'
    | '/recharger'
    | '/tutoriel-partenaire'
    | '/en/about'
    | '/en/accounting-firm-abidjan'
    | '/en/company-registration-ivory-coast'
    | '/en/contact-us'
    | '/en/get-quotes'
    | '/en/logo-offer'
    | '/en/start-a-business-ivory-coast'
    | '/en/thank-you'
    | '/en/website-offer'
    | '/guides/$slug'
    | '/en'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/chariow-webhook'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/lead-upsell'
    | '/api/public/meta-capi'
    | '/api/public/test-partner-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/blog'
    | '/cabinet-comptable-abidjan'
    | '/cabinets-comptables-partenaires'
    | '/changer-mot-de-passe'
    | '/comment-ca-marche'
    | '/comptabilite-entreprise-abidjan'
    | '/connexion'
    | '/creation-entreprise-cote-divoire'
    | '/creation-entreprise-diaspora-ivoirienne'
    | '/creer-son-entreprise-cote-divoire'
    | '/declaration-fiscale-cote-divoire'
    | '/demande-soumissions'
    | '/domiciliation-entreprise-abidjan'
    | '/faq'
    | '/guides'
    | '/inscription-partenaire'
    | '/mcp'
    | '/merci'
    | '/mot-de-passe-oublie'
    | '/nous-contacter'
    | '/offre-logo'
    | '/offre-site-internet'
    | '/reinitialiser-mot-de-passe'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/espace-partenaire'
    | '/_authenticated/historique'
    | '/_authenticated/marketplace'
    | '/_authenticated/recharger'
    | '/_authenticated/tutoriel-partenaire'
    | '/en/about'
    | '/en/accounting-firm-abidjan'
    | '/en/company-registration-ivory-coast'
    | '/en/contact-us'
    | '/en/get-quotes'
    | '/en/logo-offer'
    | '/en/start-a-business-ivory-coast'
    | '/en/thank-you'
    | '/en/website-offer'
    | '/guides/$slug'
    | '/en/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/chariow-webhook'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/lead-upsell'
    | '/api/public/meta-capi'
    | '/api/public/test-partner-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRoute
  CabinetComptableAbidjanRoute: typeof CabinetComptableAbidjanRoute
  CabinetsComptablesPartenairesRoute: typeof CabinetsComptablesPartenairesRoute
  ChangerMotDePasseRoute: typeof ChangerMotDePasseRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ComptabiliteEntrepriseAbidjanRoute: typeof ComptabiliteEntrepriseAbidjanRoute
  ConnexionRoute: typeof ConnexionRoute
  CreationEntrepriseCoteDivoireRoute: typeof CreationEntrepriseCoteDivoireRoute
  CreationEntrepriseDiasporaIvoirienneRoute: typeof CreationEntrepriseDiasporaIvoirienneRoute
  CreerSonEntrepriseCoteDivoireRoute: typeof CreerSonEntrepriseCoteDivoireRoute
  DeclarationFiscaleCoteDivoireRoute: typeof DeclarationFiscaleCoteDivoireRoute
  DemandeSoumissionsRoute: typeof DemandeSoumissionsRoute
  DomiciliationEntrepriseAbidjanRoute: typeof DomiciliationEntrepriseAbidjanRoute
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  InscriptionPartenaireRoute: typeof InscriptionPartenaireRoute
  McpRoute: typeof McpRoute
  MerciRoute: typeof MerciRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NousContacterRoute: typeof NousContacterRoute
  OffreLogoRoute: typeof OffreLogoRoute
  OffreSiteInternetRoute: typeof OffreSiteInternetRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EnAboutRoute: typeof EnAboutRoute
  EnAccountingFirmAbidjanRoute: typeof EnAccountingFirmAbidjanRoute
  EnCompanyRegistrationIvoryCoastRoute: typeof EnCompanyRegistrationIvoryCoastRoute
  EnContactUsRoute: typeof EnContactUsRoute
  EnGetQuotesRoute: typeof EnGetQuotesRoute
  EnLogoOfferRoute: typeof EnLogoOfferRoute
  EnStartABusinessIvoryCoastRoute: typeof EnStartABusinessIvoryCoastRoute
  EnThankYouRoute: typeof EnThankYouRoute
  EnWebsiteOfferRoute: typeof EnWebsiteOfferRoute
  EnIndexRoute: typeof EnIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicChariowWebhookRoute: typeof ApiPublicChariowWebhookRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicLeadUpsellRoute: typeof ApiPublicLeadUpsellRoute
  ApiPublicMetaCapiRoute: typeof ApiPublicMetaCapiRoute
  ApiPublicTestPartnerWebhookRoute: typeof ApiPublicTestPartnerWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offre-site-internet': {
      id: '/offre-site-internet'
      path: '/offre-site-internet'
      fullPath: '/offre-site-internet'
      preLoaderRoute: typeof OffreSiteInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offre-logo': {
      id: '/offre-logo'
      path: '/offre-logo'
      fullPath: '/offre-logo'
      preLoaderRoute: typeof OffreLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nous-contacter': {
      id: '/nous-contacter'
      path: '/nous-contacter'
      fullPath: '/nous-contacter'
      preLoaderRoute: typeof NousContacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-partenaire': {
      id: '/inscription-partenaire'
      path: '/inscription-partenaire'
      fullPath: '/inscription-partenaire'
      preLoaderRoute: typeof InscriptionPartenaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domiciliation-entreprise-abidjan': {
      id: '/domiciliation-entreprise-abidjan'
      path: '/domiciliation-entreprise-abidjan'
      fullPath: '/domiciliation-entreprise-abidjan'
      preLoaderRoute: typeof DomiciliationEntrepriseAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande-soumissions': {
      id: '/demande-soumissions'
      path: '/demande-soumissions'
      fullPath: '/demande-soumissions'
      preLoaderRoute: typeof DemandeSoumissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declaration-fiscale-cote-divoire': {
      id: '/declaration-fiscale-cote-divoire'
      path: '/declaration-fiscale-cote-divoire'
      fullPath: '/declaration-fiscale-cote-divoire'
      preLoaderRoute: typeof DeclarationFiscaleCoteDivoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creer-son-entreprise-cote-divoire': {
      id: '/creer-son-entreprise-cote-divoire'
      path: '/creer-son-entreprise-cote-divoire'
      fullPath: '/creer-son-entreprise-cote-divoire'
      preLoaderRoute: typeof CreerSonEntrepriseCoteDivoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-entreprise-diaspora-ivoirienne': {
      id: '/creation-entreprise-diaspora-ivoirienne'
      path: '/creation-entreprise-diaspora-ivoirienne'
      fullPath: '/creation-entreprise-diaspora-ivoirienne'
      preLoaderRoute: typeof CreationEntrepriseDiasporaIvoirienneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-entreprise-cote-divoire': {
      id: '/creation-entreprise-cote-divoire'
      path: '/creation-entreprise-cote-divoire'
      fullPath: '/creation-entreprise-cote-divoire'
      preLoaderRoute: typeof CreationEntrepriseCoteDivoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptabilite-entreprise-abidjan': {
      id: '/comptabilite-entreprise-abidjan'
      path: '/comptabilite-entreprise-abidjan'
      fullPath: '/comptabilite-entreprise-abidjan'
      preLoaderRoute: typeof ComptabiliteEntrepriseAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changer-mot-de-passe': {
      id: '/changer-mot-de-passe'
      path: '/changer-mot-de-passe'
      fullPath: '/changer-mot-de-passe'
      preLoaderRoute: typeof ChangerMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinets-comptables-partenaires': {
      id: '/cabinets-comptables-partenaires'
      path: '/cabinets-comptables-partenaires'
      fullPath: '/cabinets-comptables-partenaires'
      preLoaderRoute: typeof CabinetsComptablesPartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet-comptable-abidjan': {
      id: '/cabinet-comptable-abidjan'
      path: '/cabinet-comptable-abidjan'
      fullPath: '/cabinet-comptable-abidjan'
      preLoaderRoute: typeof CabinetComptableAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/en/website-offer': {
      id: '/en/website-offer'
      path: '/en/website-offer'
      fullPath: '/en/website-offer'
      preLoaderRoute: typeof EnWebsiteOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/thank-you': {
      id: '/en/thank-you'
      path: '/en/thank-you'
      fullPath: '/en/thank-you'
      preLoaderRoute: typeof EnThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/start-a-business-ivory-coast': {
      id: '/en/start-a-business-ivory-coast'
      path: '/en/start-a-business-ivory-coast'
      fullPath: '/en/start-a-business-ivory-coast'
      preLoaderRoute: typeof EnStartABusinessIvoryCoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/logo-offer': {
      id: '/en/logo-offer'
      path: '/en/logo-offer'
      fullPath: '/en/logo-offer'
      preLoaderRoute: typeof EnLogoOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/get-quotes': {
      id: '/en/get-quotes'
      path: '/en/get-quotes'
      fullPath: '/en/get-quotes'
      preLoaderRoute: typeof EnGetQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact-us': {
      id: '/en/contact-us'
      path: '/en/contact-us'
      fullPath: '/en/contact-us'
      preLoaderRoute: typeof EnContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/company-registration-ivory-coast': {
      id: '/en/company-registration-ivory-coast'
      path: '/en/company-registration-ivory-coast'
      fullPath: '/en/company-registration-ivory-coast'
      preLoaderRoute: typeof EnCompanyRegistrationIvoryCoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/accounting-firm-abidjan': {
      id: '/en/accounting-firm-abidjan'
      path: '/en/accounting-firm-abidjan'
      fullPath: '/en/accounting-firm-abidjan'
      preLoaderRoute: typeof EnAccountingFirmAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutoriel-partenaire': {
      id: '/_authenticated/tutoriel-partenaire'
      path: '/tutoriel-partenaire'
      fullPath: '/tutoriel-partenaire'
      preLoaderRoute: typeof AuthenticatedTutorielPartenaireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recharger': {
      id: '/_authenticated/recharger'
      path: '/recharger'
      fullPath: '/recharger'
      preLoaderRoute: typeof AuthenticatedRechargerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espace-partenaire': {
      id: '/_authenticated/espace-partenaire'
      path: '/espace-partenaire'
      fullPath: '/espace-partenaire'
      preLoaderRoute: typeof AuthenticatedEspacePartenaireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-partner-webhook': {
      id: '/api/public/test-partner-webhook'
      path: '/api/public/test-partner-webhook'
      fullPath: '/api/public/test-partner-webhook'
      preLoaderRoute: typeof ApiPublicTestPartnerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-capi': {
      id: '/api/public/meta-capi'
      path: '/api/public/meta-capi'
      fullPath: '/api/public/meta-capi'
      preLoaderRoute: typeof ApiPublicMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-upsell': {
      id: '/api/public/lead-upsell'
      path: '/api/public/lead-upsell'
      fullPath: '/api/public/lead-upsell'
      preLoaderRoute: typeof ApiPublicLeadUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chariow-webhook': {
      id: '/api/public/chariow-webhook'
      path: '/api/public/chariow-webhook'
      fullPath: '/api/public/chariow-webhook'
      preLoaderRoute: typeof ApiPublicChariowWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEspacePartenaireRoute: typeof AuthenticatedEspacePartenaireRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedRechargerRoute: typeof AuthenticatedRechargerRoute
  AuthenticatedTutorielPartenaireRoute: typeof AuthenticatedTutorielPartenaireRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEspacePartenaireRoute: AuthenticatedEspacePartenaireRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedRechargerRoute: AuthenticatedRechargerRoute,
  AuthenticatedTutorielPartenaireRoute: AuthenticatedTutorielPartenaireRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRoute,
  CabinetComptableAbidjanRoute: CabinetComptableAbidjanRoute,
  CabinetsComptablesPartenairesRoute: CabinetsComptablesPartenairesRoute,
  ChangerMotDePasseRoute: ChangerMotDePasseRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ComptabiliteEntrepriseAbidjanRoute: ComptabiliteEntrepriseAbidjanRoute,
  ConnexionRoute: ConnexionRoute,
  CreationEntrepriseCoteDivoireRoute: CreationEntrepriseCoteDivoireRoute,
  CreationEntrepriseDiasporaIvoirienneRoute:
    CreationEntrepriseDiasporaIvoirienneRoute,
  CreerSonEntrepriseCoteDivoireRoute: CreerSonEntrepriseCoteDivoireRoute,
  DeclarationFiscaleCoteDivoireRoute: DeclarationFiscaleCoteDivoireRoute,
  DemandeSoumissionsRoute: DemandeSoumissionsRoute,
  DomiciliationEntrepriseAbidjanRoute: DomiciliationEntrepriseAbidjanRoute,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRouteWithChildren,
  InscriptionPartenaireRoute: InscriptionPartenaireRoute,
  McpRoute: McpRoute,
  MerciRoute: MerciRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NousContacterRoute: NousContacterRoute,
  OffreLogoRoute: OffreLogoRoute,
  OffreSiteInternetRoute: OffreSiteInternetRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EnAboutRoute: EnAboutRoute,
  EnAccountingFirmAbidjanRoute: EnAccountingFirmAbidjanRoute,
  EnCompanyRegistrationIvoryCoastRoute: EnCompanyRegistrationIvoryCoastRoute,
  EnContactUsRoute: EnContactUsRoute,
  EnGetQuotesRoute: EnGetQuotesRoute,
  EnLogoOfferRoute: EnLogoOfferRoute,
  EnStartABusinessIvoryCoastRoute: EnStartABusinessIvoryCoastRoute,
  EnThankYouRoute: EnThankYouRoute,
  EnWebsiteOfferRoute: EnWebsiteOfferRoute,
  EnIndexRoute: EnIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicChariowWebhookRoute: ApiPublicChariowWebhookRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicLeadUpsellRoute: ApiPublicLeadUpsellRoute,
  ApiPublicMetaCapiRoute: ApiPublicMetaCapiRoute,
  ApiPublicTestPartnerWebhookRoute: ApiPublicTestPartnerWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
