/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OffreSiteInternetRouteImport } from './routes/offre-site-internet'
import { Route as OffreLogoRouteImport } from './routes/offre-logo'
import { Route as NousContacterRouteImport } from './routes/nous-contacter'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DomiciliationEntrepriseAbidjanRouteImport } from './routes/domiciliation-entreprise-abidjan'
import { Route as DemandeSoumissionsRouteImport } from './routes/demande-soumissions'
import { Route as DeclarationFiscaleCoteDivoireRouteImport } from './routes/declaration-fiscale-cote-divoire'
import { Route as CreationEntrepriseDiasporaIvoirienneRouteImport } from './routes/creation-entreprise-diaspora-ivoirienne'
import { Route as CreationEntrepriseCoteDivoireRouteImport } from './routes/creation-entreprise-cote-divoire'
import { Route as ComptabiliteEntrepriseAbidjanRouteImport } from './routes/comptabilite-entreprise-abidjan'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as CabinetsComptablesPartenairesRouteImport } from './routes/cabinets-comptables-partenaires'
import { Route as CabinetComptableAbidjanRouteImport } from './routes/cabinet-comptable-abidjan'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as EnWebsiteOfferRouteImport } from './routes/en/website-offer'
import { Route as EnThankYouRouteImport } from './routes/en/thank-you'
import { Route as EnLogoOfferRouteImport } from './routes/en/logo-offer'
import { Route as EnGetQuotesRouteImport } from './routes/en/get-quotes'
import { Route as EnContactUsRouteImport } from './routes/en/contact-us'
import { Route as EnCompanyRegistrationIvoryCoastRouteImport } from './routes/en/company-registration-ivory-coast'
import { Route as EnAccountingFirmAbidjanRouteImport } from './routes/en/accounting-firm-abidjan'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as ApiPublicLeadUpsellRouteImport } from './routes/api/public/lead-upsell'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OffreSiteInternetRoute = OffreSiteInternetRouteImport.update({
  id: '/offre-site-internet',
  path: '/offre-site-internet',
  getParentRoute: () => rootRouteImport,
} as any)
const OffreLogoRoute = OffreLogoRouteImport.update({
  id: '/offre-logo',
  path: '/offre-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const NousContacterRoute = NousContacterRouteImport.update({
  id: '/nous-contacter',
  path: '/nous-contacter',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DomiciliationEntrepriseAbidjanRoute =
  DomiciliationEntrepriseAbidjanRouteImport.update({
    id: '/domiciliation-entreprise-abidjan',
    path: '/domiciliation-entreprise-abidjan',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemandeSoumissionsRoute = DemandeSoumissionsRouteImport.update({
  id: '/demande-soumissions',
  path: '/demande-soumissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclarationFiscaleCoteDivoireRoute =
  DeclarationFiscaleCoteDivoireRouteImport.update({
    id: '/declaration-fiscale-cote-divoire',
    path: '/declaration-fiscale-cote-divoire',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreationEntrepriseDiasporaIvoirienneRoute =
  CreationEntrepriseDiasporaIvoirienneRouteImport.update({
    id: '/creation-entreprise-diaspora-ivoirienne',
    path: '/creation-entreprise-diaspora-ivoirienne',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreationEntrepriseCoteDivoireRoute =
  CreationEntrepriseCoteDivoireRouteImport.update({
    id: '/creation-entreprise-cote-divoire',
    path: '/creation-entreprise-cote-divoire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComptabiliteEntrepriseAbidjanRoute =
  ComptabiliteEntrepriseAbidjanRouteImport.update({
    id: '/comptabilite-entreprise-abidjan',
    path: '/comptabilite-entreprise-abidjan',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetsComptablesPartenairesRoute =
  CabinetsComptablesPartenairesRouteImport.update({
    id: '/cabinets-comptables-partenaires',
    path: '/cabinets-comptables-partenaires',
    getParentRoute: () => rootRouteImport,
  } as any)
const CabinetComptableAbidjanRoute = CabinetComptableAbidjanRouteImport.update({
  id: '/cabinet-comptable-abidjan',
  path: '/cabinet-comptable-abidjan',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const EnWebsiteOfferRoute = EnWebsiteOfferRouteImport.update({
  id: '/en/website-offer',
  path: '/en/website-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnThankYouRoute = EnThankYouRouteImport.update({
  id: '/en/thank-you',
  path: '/en/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLogoOfferRoute = EnLogoOfferRouteImport.update({
  id: '/en/logo-offer',
  path: '/en/logo-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGetQuotesRoute = EnGetQuotesRouteImport.update({
  id: '/en/get-quotes',
  path: '/en/get-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactUsRoute = EnContactUsRouteImport.update({
  id: '/en/contact-us',
  path: '/en/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCompanyRegistrationIvoryCoastRoute =
  EnCompanyRegistrationIvoryCoastRouteImport.update({
    id: '/en/company-registration-ivory-coast',
    path: '/en/company-registration-ivory-coast',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnAccountingFirmAbidjanRoute = EnAccountingFirmAbidjanRouteImport.update({
  id: '/en/accounting-firm-abidjan',
  path: '/en/accounting-firm-abidjan',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadUpsellRoute = ApiPublicLeadUpsellRouteImport.update({
  id: '/api/public/lead-upsell',
  path: '/api/public/lead-upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/cabinet-comptable-abidjan': typeof CabinetComptableAbidjanRoute
  '/cabinets-comptables-partenaires': typeof CabinetsComptablesPartenairesRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comptabilite-entreprise-abidjan': typeof ComptabiliteEntrepriseAbidjanRoute
  '/creation-entreprise-cote-divoire': typeof CreationEntrepriseCoteDivoireRoute
  '/creation-entreprise-diaspora-ivoirienne': typeof CreationEntrepriseDiasporaIvoirienneRoute
  '/declaration-fiscale-cote-divoire': typeof DeclarationFiscaleCoteDivoireRoute
  '/demande-soumissions': typeof DemandeSoumissionsRoute
  '/domiciliation-entreprise-abidjan': typeof DomiciliationEntrepriseAbidjanRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/merci': typeof MerciRoute
  '/nous-contacter': typeof NousContacterRoute
  '/offre-logo': typeof OffreLogoRoute
  '/offre-site-internet': typeof OffreSiteInternetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-abidjan': typeof EnAccountingFirmAbidjanRoute
  '/en/company-registration-ivory-coast': typeof EnCompanyRegistrationIvoryCoastRoute
  '/en/contact-us': typeof EnContactUsRoute
  '/en/get-quotes': typeof EnGetQuotesRoute
  '/en/logo-offer': typeof EnLogoOfferRoute
  '/en/thank-you': typeof EnThankYouRoute
  '/en/website-offer': typeof EnWebsiteOfferRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en/': typeof EnIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/lead-upsell': typeof ApiPublicLeadUpsellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/cabinet-comptable-abidjan': typeof CabinetComptableAbidjanRoute
  '/cabinets-comptables-partenaires': typeof CabinetsComptablesPartenairesRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comptabilite-entreprise-abidjan': typeof ComptabiliteEntrepriseAbidjanRoute
  '/creation-entreprise-cote-divoire': typeof CreationEntrepriseCoteDivoireRoute
  '/creation-entreprise-diaspora-ivoirienne': typeof CreationEntrepriseDiasporaIvoirienneRoute
  '/declaration-fiscale-cote-divoire': typeof DeclarationFiscaleCoteDivoireRoute
  '/demande-soumissions': typeof DemandeSoumissionsRoute
  '/domiciliation-entreprise-abidjan': typeof DomiciliationEntrepriseAbidjanRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/merci': typeof MerciRoute
  '/nous-contacter': typeof NousContacterRoute
  '/offre-logo': typeof OffreLogoRoute
  '/offre-site-internet': typeof OffreSiteInternetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-abidjan': typeof EnAccountingFirmAbidjanRoute
  '/en/company-registration-ivory-coast': typeof EnCompanyRegistrationIvoryCoastRoute
  '/en/contact-us': typeof EnContactUsRoute
  '/en/get-quotes': typeof EnGetQuotesRoute
  '/en/logo-offer': typeof EnLogoOfferRoute
  '/en/thank-you': typeof EnThankYouRoute
  '/en/website-offer': typeof EnWebsiteOfferRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en': typeof EnIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/lead-upsell': typeof ApiPublicLeadUpsellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/cabinet-comptable-abidjan': typeof CabinetComptableAbidjanRoute
  '/cabinets-comptables-partenaires': typeof CabinetsComptablesPartenairesRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/comptabilite-entreprise-abidjan': typeof ComptabiliteEntrepriseAbidjanRoute
  '/creation-entreprise-cote-divoire': typeof CreationEntrepriseCoteDivoireRoute
  '/creation-entreprise-diaspora-ivoirienne': typeof CreationEntrepriseDiasporaIvoirienneRoute
  '/declaration-fiscale-cote-divoire': typeof DeclarationFiscaleCoteDivoireRoute
  '/demande-soumissions': typeof DemandeSoumissionsRoute
  '/domiciliation-entreprise-abidjan': typeof DomiciliationEntrepriseAbidjanRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/merci': typeof MerciRoute
  '/nous-contacter': typeof NousContacterRoute
  '/offre-logo': typeof OffreLogoRoute
  '/offre-site-internet': typeof OffreSiteInternetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-abidjan': typeof EnAccountingFirmAbidjanRoute
  '/en/company-registration-ivory-coast': typeof EnCompanyRegistrationIvoryCoastRoute
  '/en/contact-us': typeof EnContactUsRoute
  '/en/get-quotes': typeof EnGetQuotesRoute
  '/en/logo-offer': typeof EnLogoOfferRoute
  '/en/thank-you': typeof EnThankYouRoute
  '/en/website-offer': typeof EnWebsiteOfferRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/en/': typeof EnIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/lead-upsell': typeof ApiPublicLeadUpsellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/cabinet-comptable-abidjan'
    | '/cabinets-comptables-partenaires'
    | '/comment-ca-marche'
    | '/comptabilite-entreprise-abidjan'
    | '/creation-entreprise-cote-divoire'
    | '/creation-entreprise-diaspora-ivoirienne'
    | '/declaration-fiscale-cote-divoire'
    | '/demande-soumissions'
    | '/domiciliation-entreprise-abidjan'
    | '/faq'
    | '/guides'
    | '/merci'
    | '/nous-contacter'
    | '/offre-logo'
    | '/offre-site-internet'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/accounting-firm-abidjan'
    | '/en/company-registration-ivory-coast'
    | '/en/contact-us'
    | '/en/get-quotes'
    | '/en/logo-offer'
    | '/en/thank-you'
    | '/en/website-offer'
    | '/guides/$slug'
    | '/en/'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/lead-upsell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/cabinet-comptable-abidjan'
    | '/cabinets-comptables-partenaires'
    | '/comment-ca-marche'
    | '/comptabilite-entreprise-abidjan'
    | '/creation-entreprise-cote-divoire'
    | '/creation-entreprise-diaspora-ivoirienne'
    | '/declaration-fiscale-cote-divoire'
    | '/demande-soumissions'
    | '/domiciliation-entreprise-abidjan'
    | '/faq'
    | '/guides'
    | '/merci'
    | '/nous-contacter'
    | '/offre-logo'
    | '/offre-site-internet'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/accounting-firm-abidjan'
    | '/en/company-registration-ivory-coast'
    | '/en/contact-us'
    | '/en/get-quotes'
    | '/en/logo-offer'
    | '/en/thank-you'
    | '/en/website-offer'
    | '/guides/$slug'
    | '/en'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/lead-upsell'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/blog'
    | '/cabinet-comptable-abidjan'
    | '/cabinets-comptables-partenaires'
    | '/comment-ca-marche'
    | '/comptabilite-entreprise-abidjan'
    | '/creation-entreprise-cote-divoire'
    | '/creation-entreprise-diaspora-ivoirienne'
    | '/declaration-fiscale-cote-divoire'
    | '/demande-soumissions'
    | '/domiciliation-entreprise-abidjan'
    | '/faq'
    | '/guides'
    | '/merci'
    | '/nous-contacter'
    | '/offre-logo'
    | '/offre-site-internet'
    | '/sitemap.xml'
    | '/en/about'
    | '/en/accounting-firm-abidjan'
    | '/en/company-registration-ivory-coast'
    | '/en/contact-us'
    | '/en/get-quotes'
    | '/en/logo-offer'
    | '/en/thank-you'
    | '/en/website-offer'
    | '/guides/$slug'
    | '/en/'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/lead-upsell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRoute
  CabinetComptableAbidjanRoute: typeof CabinetComptableAbidjanRoute
  CabinetsComptablesPartenairesRoute: typeof CabinetsComptablesPartenairesRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ComptabiliteEntrepriseAbidjanRoute: typeof ComptabiliteEntrepriseAbidjanRoute
  CreationEntrepriseCoteDivoireRoute: typeof CreationEntrepriseCoteDivoireRoute
  CreationEntrepriseDiasporaIvoirienneRoute: typeof CreationEntrepriseDiasporaIvoirienneRoute
  DeclarationFiscaleCoteDivoireRoute: typeof DeclarationFiscaleCoteDivoireRoute
  DemandeSoumissionsRoute: typeof DemandeSoumissionsRoute
  DomiciliationEntrepriseAbidjanRoute: typeof DomiciliationEntrepriseAbidjanRoute
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  MerciRoute: typeof MerciRoute
  NousContacterRoute: typeof NousContacterRoute
  OffreLogoRoute: typeof OffreLogoRoute
  OffreSiteInternetRoute: typeof OffreSiteInternetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnAboutRoute: typeof EnAboutRoute
  EnAccountingFirmAbidjanRoute: typeof EnAccountingFirmAbidjanRoute
  EnCompanyRegistrationIvoryCoastRoute: typeof EnCompanyRegistrationIvoryCoastRoute
  EnContactUsRoute: typeof EnContactUsRoute
  EnGetQuotesRoute: typeof EnGetQuotesRoute
  EnLogoOfferRoute: typeof EnLogoOfferRoute
  EnThankYouRoute: typeof EnThankYouRoute
  EnWebsiteOfferRoute: typeof EnWebsiteOfferRoute
  EnIndexRoute: typeof EnIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicLeadUpsellRoute: typeof ApiPublicLeadUpsellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offre-site-internet': {
      id: '/offre-site-internet'
      path: '/offre-site-internet'
      fullPath: '/offre-site-internet'
      preLoaderRoute: typeof OffreSiteInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offre-logo': {
      id: '/offre-logo'
      path: '/offre-logo'
      fullPath: '/offre-logo'
      preLoaderRoute: typeof OffreLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nous-contacter': {
      id: '/nous-contacter'
      path: '/nous-contacter'
      fullPath: '/nous-contacter'
      preLoaderRoute: typeof NousContacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domiciliation-entreprise-abidjan': {
      id: '/domiciliation-entreprise-abidjan'
      path: '/domiciliation-entreprise-abidjan'
      fullPath: '/domiciliation-entreprise-abidjan'
      preLoaderRoute: typeof DomiciliationEntrepriseAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande-soumissions': {
      id: '/demande-soumissions'
      path: '/demande-soumissions'
      fullPath: '/demande-soumissions'
      preLoaderRoute: typeof DemandeSoumissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declaration-fiscale-cote-divoire': {
      id: '/declaration-fiscale-cote-divoire'
      path: '/declaration-fiscale-cote-divoire'
      fullPath: '/declaration-fiscale-cote-divoire'
      preLoaderRoute: typeof DeclarationFiscaleCoteDivoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-entreprise-diaspora-ivoirienne': {
      id: '/creation-entreprise-diaspora-ivoirienne'
      path: '/creation-entreprise-diaspora-ivoirienne'
      fullPath: '/creation-entreprise-diaspora-ivoirienne'
      preLoaderRoute: typeof CreationEntrepriseDiasporaIvoirienneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-entreprise-cote-divoire': {
      id: '/creation-entreprise-cote-divoire'
      path: '/creation-entreprise-cote-divoire'
      fullPath: '/creation-entreprise-cote-divoire'
      preLoaderRoute: typeof CreationEntrepriseCoteDivoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptabilite-entreprise-abidjan': {
      id: '/comptabilite-entreprise-abidjan'
      path: '/comptabilite-entreprise-abidjan'
      fullPath: '/comptabilite-entreprise-abidjan'
      preLoaderRoute: typeof ComptabiliteEntrepriseAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinets-comptables-partenaires': {
      id: '/cabinets-comptables-partenaires'
      path: '/cabinets-comptables-partenaires'
      fullPath: '/cabinets-comptables-partenaires'
      preLoaderRoute: typeof CabinetsComptablesPartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet-comptable-abidjan': {
      id: '/cabinet-comptable-abidjan'
      path: '/cabinet-comptable-abidjan'
      fullPath: '/cabinet-comptable-abidjan'
      preLoaderRoute: typeof CabinetComptableAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/en/website-offer': {
      id: '/en/website-offer'
      path: '/en/website-offer'
      fullPath: '/en/website-offer'
      preLoaderRoute: typeof EnWebsiteOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/thank-you': {
      id: '/en/thank-you'
      path: '/en/thank-you'
      fullPath: '/en/thank-you'
      preLoaderRoute: typeof EnThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/logo-offer': {
      id: '/en/logo-offer'
      path: '/en/logo-offer'
      fullPath: '/en/logo-offer'
      preLoaderRoute: typeof EnLogoOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/get-quotes': {
      id: '/en/get-quotes'
      path: '/en/get-quotes'
      fullPath: '/en/get-quotes'
      preLoaderRoute: typeof EnGetQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact-us': {
      id: '/en/contact-us'
      path: '/en/contact-us'
      fullPath: '/en/contact-us'
      preLoaderRoute: typeof EnContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/company-registration-ivory-coast': {
      id: '/en/company-registration-ivory-coast'
      path: '/en/company-registration-ivory-coast'
      fullPath: '/en/company-registration-ivory-coast'
      preLoaderRoute: typeof EnCompanyRegistrationIvoryCoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/accounting-firm-abidjan': {
      id: '/en/accounting-firm-abidjan'
      path: '/en/accounting-firm-abidjan'
      fullPath: '/en/accounting-firm-abidjan'
      preLoaderRoute: typeof EnAccountingFirmAbidjanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-upsell': {
      id: '/api/public/lead-upsell'
      path: '/api/public/lead-upsell'
      fullPath: '/api/public/lead-upsell'
      preLoaderRoute: typeof ApiPublicLeadUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRoute,
  CabinetComptableAbidjanRoute: CabinetComptableAbidjanRoute,
  CabinetsComptablesPartenairesRoute: CabinetsComptablesPartenairesRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ComptabiliteEntrepriseAbidjanRoute: ComptabiliteEntrepriseAbidjanRoute,
  CreationEntrepriseCoteDivoireRoute: CreationEntrepriseCoteDivoireRoute,
  CreationEntrepriseDiasporaIvoirienneRoute:
    CreationEntrepriseDiasporaIvoirienneRoute,
  DeclarationFiscaleCoteDivoireRoute: DeclarationFiscaleCoteDivoireRoute,
  DemandeSoumissionsRoute: DemandeSoumissionsRoute,
  DomiciliationEntrepriseAbidjanRoute: DomiciliationEntrepriseAbidjanRoute,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRouteWithChildren,
  MerciRoute: MerciRoute,
  NousContacterRoute: NousContacterRoute,
  OffreLogoRoute: OffreLogoRoute,
  OffreSiteInternetRoute: OffreSiteInternetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnAboutRoute: EnAboutRoute,
  EnAccountingFirmAbidjanRoute: EnAccountingFirmAbidjanRoute,
  EnCompanyRegistrationIvoryCoastRoute: EnCompanyRegistrationIvoryCoastRoute,
  EnContactUsRoute: EnContactUsRoute,
  EnGetQuotesRoute: EnGetQuotesRoute,
  EnLogoOfferRoute: EnLogoOfferRoute,
  EnThankYouRoute: EnThankYouRoute,
  EnWebsiteOfferRoute: EnWebsiteOfferRoute,
  EnIndexRoute: EnIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicLeadUpsellRoute: ApiPublicLeadUpsellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
